@startuml
 
' ===================
' Classes and Attributes
' ===================
 
class "tree::Relation" {
 + tree:path
 + tree:remainingItems : int
 + tree:value
}
 
class "tree::Node" {
 + ldes:immutable : boolean
}
 
class "tree::Collection" {
 + tree:member
}
 
class "sh::NodeShape"
 
class "dcat::Distribution"

class "dcat::DataService"

class "tree::SearchTree"
 
class "ldes::RetentionPolicy" {
 + ldes:fullLogDuration
 + ldes:startingFrom : dateTime
 + ldes:versionAmount
 + ldes:versionDeleteDuration : duration
 + ldes:versionDuration : duration
}
 
class "ldes::EventStream" {
 + ldes:pollingInterval : int
 + ldes:sequencePath
 + ldes:timestampPath
 + ldes:versionOfPath
 + ldes:versionSequencePath
 + ldes:versionTimestampPath
}
 
class "ldes::EventSource" {
 + ldes:transactionFinalizedObject
 + ldes:transactionFinalizedPath
 + ldes:transactionPath
 + ldes:versionCreateObject
 + ldes:versionCreatePath
 + ldes:versionDeleteObject
 + ldes:versionDeletePath
 + ldes:versionUpdateObject
 + ldes:versionUpdatePath
}
 
' ===================
' Relationships
' ===================
 
"tree::Node" --> "tree::SearchTree" : tree:viewDescription
"tree::Node" --> "dcat::Distribution" : tree:viewDescription
"tree::Node" --> "dcat::DataService" : tree:viewDescription
"tree::Node" --> "ldes::RetentionPolicy" : ldes:retentionPolicy
"tree::Node" --> "tree::Relation" : tree:relation
"tree::Relation" --> "tree::Node" : tree:node
"tree::Collection" --> "tree::Node" : tree:view
"tree::Collection" --> "sh::NodeShape" : tree:shape
"tree::Collection" <|-- "ldes::EventStream"
"dcat::Distribution" <|-- "ldes::EventSource"
"ldes::EventStream" --> "ldes::EventSource" : tree:viewDescription

@enduml
