name: LDES Vocabulary Build

on:
  pull_request:
    paths: ["vocabulary.bs"]
  push:
    branches: [main]
    paths: ["vocabulary.bs"]
    tags: ["*"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish Bikeshed document
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed

          # Modify as appropriate
          GH_PAGES_BRANCH: gh-pages
          # The source file
          SOURCE: vocabulary.bs

          # output filename defaults to your input
          # with .html extension instead,
          # but if you want to customize it:
          DESTINATION: vocabulary.html
          
  copy-tag-version:
    name: Copy tag snapshot
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Copy vocabulary snapshot
        run: |
          set -euo pipefail
          tag="${GITHUB_REF_NAME}"
          dest="versions/${tag}"
          mkdir -p "${dest}"
          cp vocabulary.html "${dest}/vocabulary.html"
          if git status --porcelain | grep . >/dev/null; then
            git config user.email "semic-eu+github-actions[bot]@users.noreply.github.com"
            git config user.name "SEMIC EU archival [bot]"
            git add "${dest}/vocabulary.html"
            git commit -m "Add vocabulary snapshot for ${tag}"
            git push
          else
            echo "No changes to commit."